services:
  - type: web
    name: auction-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OMNIDIMENSION_API_KEY
        sync: false
