services:
  - type: web
    name: omnidimension-auction
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: OMNIDIMENSION_API_KEY
        value: pZ3frbfFOsjvsvlxBL1le7-YLcCiWSqas12v2CiwC8k
      - key: OMNIDIMENSION_WEBHOOK_URL
        value: https://backend.omnidim.io/web_widget.js?secret_key=882b84771c2d5cac884578217aaad742
    plan: free
    autoDeploy: true
